In [1]:
import numpy as np
import pandas as pd

In [25]:
df = (pd.read_csv('Phase_diagram_complexity_data.csv', header=1).T).iloc[1:, :]

In [35]:
df['mean'] = df.mean(axis=1)
df['std_error'] = df.std(axis=1) / np.sqrt(df.iloc[0].size - 1)

In [36]:
df

0          1          2          3          4          5  \
P1C0    1.168814   1.155842   1.126928   1.191801   1.148944   1.170973   
P1C1   19.122476  16.572574  18.055866  20.137123  17.564277  18.978205   
P1C2    8.826106  10.102953   8.083814   8.126261   8.793352   8.830448   
P2C0    0.000328   0.000199   0.000215   0.000115   0.000321   0.000206   
P2C1    0.056523   0.435265  -1.177725  -0.036574   0.830316   0.401435   
P2C2   -0.022358   0.037114   0.034758   0.005300  -0.020061   0.036381   
P3C0    0.000187   0.000078   0.000130   0.000087   0.000068   0.000149   
P3C1    0.444780   0.051644  -0.279336  -0.747999   0.062941  -0.004967   
P3C2    0.003918  -0.032101  -0.037057   0.180893   0.009075   0.014330   
P4C0    0.000232   0.000115   0.000176   0.000376   0.000372   0.000260   
P4C1    0.261662  -0.384595   0.493968  -0.072092   0.267028   0.320996   
P4C2   -0.006093  -0.001807  -0.019031   0.014699   0.040490  -0.022285   
P5C0    0.000180   0.000356   0.000164   0.000112   0.000103   0.000096   
P5C1   -0.013142   0.243207   0.241212   0.351864  -0.739633  -0.106121   
P5C2    0.019019  -0.107136   0.020052  -0.066887  -0.055493   0.014974   
P6C0    0.000229   0.000335   0.000408   0.000380   0.000279   0.000350   
P6C1    0.958106   0.093318   0.094222  -0.996618   0.161157  -0.571234   
P6C2   -0.008996   0.061030   0.023241  -0.113777   0.029574   0.017971   
P7C0    0.000071   0.000276   0.000146   0.000125   0.000105   0.000244   
P7C1   -1.076544  -0.787415   0.198339  -0.531524  -0.745116   0.475094   
P7C2   -0.000277   0.095329   0.010269  -0.001477  -0.003545   0.019483   
P8C0    0.000057   0.000042   0.000184   0.000039   0.000088   0.000059   
P8C1    0.078157  -0.255399   0.031858  -0.036698   0.461903  -0.115636   
P8C2    0.004193   0.012989  -0.002585   0.034435   0.010125   0.026207   
P9C0    0.000108   0.000089   0.000116   0.000080   0.000067   0.000126   
P9C1   -0.052415  -0.004908   0.098780   0.357499  -0.173413  -0.043013   
P9C2   -0.002159   0.002441  -0.008092  -0.008725  -0.002097  -0.008421   
P10C0   0.000033   0.000070   0.000057   0.000085   0.000063   0.000021   
P10C1   0.111822   0.218350  -0.095132  -0.165459  -0.132381   0.140938   
P10C2   0.004552   0.001357   0.004150   0.010321   0.002712  -0.000730   
P11C0   0.000048   0.000080   0.000033   0.000068   0.000075   0.000054   
P11C1   0.079925  -0.121906   0.071142   0.012403  -0.089043   0.035316   
P11C2   0.003286  -0.000252   0.003983   0.003483  -0.000022   0.002202   
P12C0   0.000030   0.000003   0.000150   0.000025   0.000043   0.000020   
P12C1  -0.126046   0.040361  -0.118800  -0.064189  -0.020569  -0.073562   
P12C2   0.003067   0.005814   0.002951   0.000350  -0.001599   0.002784   

               6          7          8          9       mean  std_error  
P1C0    1.167936   1.169037   1.106224   1.141009   1.154751   0.007459  
P1C1   16.965305  16.809757  17.923172  16.708648  17.883740   0.361113  
P1C2    9.330149   8.799830   9.219489   7.909629   8.802203   0.197887  
P2C0    0.000100   0.000348   0.000222   0.000264   0.000232   0.000026  
P2C1    0.123416  -0.341761   1.454386  -0.506819   0.123846   0.218686  
P2C2    0.092432  -0.024495  -0.091344  -0.029318   0.001841   0.015216  
P3C0    0.000168   0.000126   0.000138   0.000093   0.000122   0.000012  
P3C1    0.910282  -0.542705   1.395945  -0.543973   0.074661   0.203813  
P3C2   -0.027277  -0.087753   0.018426   0.020530   0.006298   0.021033  
P4C0    0.000392   0.000405   0.000298   0.000110   0.000274   0.000034  
P4C1   -0.496986   0.868827   0.756575   0.594293   0.260967   0.137344  
P4C2   -0.048780  -0.009541   0.014028   0.007971  -0.003035   0.007344  
P5C0    0.000179   0.000262   0.000069   0.000158   0.000168   0.000026  
P5C1   -0.330799  -0.416511  -0.446278  -0.894548  -0.211075   0.127922  
P5C2   -0.014266   0.034403   0.038458   0.017352  -0.009952   0.014898  
P6C0    0.000241   0.000370   0.000310   0.000252   0.0

In [53]:
c0_ranked = (-np.array(df.iloc[0::3, :]['mean'])).argsort()
c1_ranked = (-np.array(df.iloc[1::3, :]['mean'])).argsort()
c2_ranked = (-np.array(df.iloc[2::3, :]['mean'])).argsort()

In [54]:
c0_ranked

array([ 0,  5,  3,  1,  4,  6,  2,  8,  7,  9, 10, 11], dtype=int64)

In [55]:
c1_ranked

array([ 0,  3,  1,  2,  9, 10,  7,  8, 11,  5,  4,  6], dtype=int64)

In [56]:
c2_ranked

array([ 0,  6,  7,  2,  5,  9, 10,  1, 11,  8,  3,  4], dtype=int64)